### ISSUE TITLE
[提议]: 结构化错误信息及其解决方法

### ISSUE THREAD

**Issue by zyxkad** [GlobeMC/crashmc.com#115]
## 问题
目前的错误分析器用了一堆`if else`加硬编码错误信息, **非常不便于维护**.

## 可能解决方案
另维护一个仓库, 存储结构化的错误信息和解决方法(json或~~自定义结构(提供快一点点的解析速度)?~~), 错误分析器使用前需要先获取数据库(也可以加一层本地storage用作缓存, 但不确定是否会超出浏览器限制)

## 例

错误信息: `errors/1.json`
```js
{
  "error": "java.util.zip.ZipException", // Java错误Class
  "message": "zip END header not found", // 详细错误信息
  "solutions": [100] // 该错误对应的解决方法的ID, 可能不止一种解决方法
}
```

由于错误解决方法可能较大，也许不会为其设立缓存
错误解决方法: `solutions/100.json`
```js
{
  // 该解决方案适用于哪些平台:
  // client表示客户端, server表示服务端; `mods`, `mods/forge` 表示mod及其loader
  "tags": ["mods"],
  // 错误简略描述, 一句话以内
  "desc": "可能在下载 Mod 文件时出现一些意外，导致 Mod 文件读取时出错。",
  // markdown格式的详细解决方案
  // "body": "Go to <https://crashmc.com/client/mods.html#mod-%E6%96%87%E4%BB%B6%E6%8D%9F%E5%9D%8F>"
  // 也许总是链接到一个网址，并使用iframe更好?
  "link_to": "https://crashmc.com/client/mods.html#mod-%E6%96%87%E4%BB%B6%E6%8D%9F%E5%9D%8F"
}
```

**Comment by zyxkad** [comment]
同时也可以用github issue template + actions方便提交未收录的错误

**Comment by zyxkad** [comment]
错误判断也可以从原来的`includes`变为判断公共子序列占比（匹配度）, 或者训练个AI(雾)

**Comment by HRxiaohu** [comment]
恰个 Q 2494292082

**Comment by HRxiaohu** [comment]
199271393

**Comment by zyxkad** [comment]
> 199271393

@HRxiaohu 哈?

**Comment by zyxkad** [comment]
目前结构化完毕的错误: <https://github.com/kmcsr/mcla-db-dev> (issue template尚未实现)

**Comment by bingling-sama** [comment]
We now have created a discussion about it, let's plan it together.
