### ISSUE TITLE
📄[UPLOAD-CRASH] 内存溢出

### ISSUE THREAD

**Issue by Pigeon0v0** [GlobeMC/crashmc.com#118]
### 描述问题

```bash
JVM 内存溢出，导致游戏崩溃
检测关键词 `EXCEPTION_ACCESS_VIOLATION (0xc0000005)`
需要注意的是，该字段只会出现在 `hs_err_pid**.log` 中，因此需要制作对应的逻辑处理
```

### 您正在进行的操作是？

```bash
来自群友提交，无法填写
```

### 崩溃日志

```bash
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ffb5c7288a1, pid=25504, tid=25880
#
# JRE version: Java(TM) SE Runtime Environment (17.0.2+8) (build 17.0.2+8-LTS-86)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (17.0.2+8-LTS-86, mixed mode, sharing, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [atio6axx.dll+0xb488a1]
```

### 操作系统

Windows

### 客户端 / 服务端

客户端

**Comment by zhuWin** [comment]
似乎所有由于OpenGL驱动崩溃而导致的游戏崩溃都有可能报0xc0000005

nvoglv32.dll / nvoglv64.dll / OPENGL32.DLL（我所知的OpenGL驱动名称，欢迎补充



尽管内存溢出可能是造成此故的最大原因。

解决方法：32位用户请稍微调低内存量（这很玄学，一般768MB/896MB为宜，多次实践证明更大的内存反而更容易导致OpenGL驱动内存溢出。）

64位用户，请确保使用64位Java。如若均使用64位，请调高内存分配量。

话说回来，我这里的使用自定义Mesa3D OpenGL驱动的 Windows 98 设备上的 Minecraft 也经常以此崩溃，不清楚原因是什么（

有时候，JVM崩溃会明确表明发生了内存溢出，以下附件为示例。
[hs_err_pid3364.log](https://github.com/GlobeMC/crashmc.com/files/12774555/hs_err_pid3364.log)
