### ISSUE TITLE
[优化] 崩溃分析时，zip 中的可用信息应当全部使用

### ISSUE THREAD

**Issue by youzi-2333** [GlobeMC/crashmc.com#126]
### 描述

如题，在崩溃分析时，要尽可能多地使用 zip 文件中的可用信息。

### 原因

例如以下崩溃报告，可用的错误信息只存在于 `游戏崩溃前的输出.txt`。因此，如果将 zip 文件直接分析，其显示未收录；但是如果单独将 `游戏崩溃前的输出.txt` 用作分析，其能够正确指出问题在于 `Night Config 库问题`。

[错误报告-2023-5-7_16.48.39.zip](https://github.com/GlobeMC/crashmc.com/files/12342177/-2023-5-7_16.48.39.zip)

---

我本来交了个 #113 理论上应该可以实现的，但是它直接导致日志没法读取了………………所以现在先交个 Issue 再说

**Comment by youzi-2333** [comment]
我的解决方案本来是这样（也可以看[这里](https://github.com/youzi-2333/crashmc.com/blob/e93d79c4d0940f58f09c71312da10e6ee2a731f9/docs/.vitepress/theme/components/Analyzer.vue#L164)）：

```js
          // 日志读取
/* 165 */ logText = ""
          for (let key in zip.files) {
            if (!zip.files[key].dir) { // 不是文件夹，则进行读取
              if (
                zip.files[key].name == "latest.log" ||                 // latest.log
/* 170 */       zip.files[key].name == "debug.log" ||                  // debug.log
                zip.files[key].name.search(/crash-(.*).txt/) != -1 ||  // crash-***.txt
                zip.files[key].name == "minecraft.log" ||              // minecraft.log
                zip.files[key].name == "游戏崩溃前的输出.txt"           // 游戏崩溃前的输出.txt（仅 PCL）
                ) {
/* 175 */       logText = logText + zip.files[key].async("string") + "\n"
              }
            }
          }
          if (logText == "") { // 啥都没读到
/* 180 */   FinishAnalysis("FetchLogErr", "(＃°Д°)")
            return
          } else { // 读到日志了，贼棒
            return logText
          }
/* 185 */})
        .then(function (content) {
          LogAnalysis(content)
        })
```

将第 `175` 行的 `zip.files[key].async("string")` 改为 `zip.files[key].await("string")` 能否解决该问题？

**Comment by zyxkad** [comment]
啊这，建议去了解一下async函数

<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function>
<https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/await>

**Comment by zyxkad** [comment]
应该改为
```js
await zip.files[key].async("string")
```

**Comment by youzi-2333** [comment]
啊啊啊啊啊啊啊，抱歉抱歉（
我去搜的时候搜不到代码，只看到别人把 async 和 await 放在一起，我就把 await 当作函数了……

**Comment by zyxkad** [comment]
没事，async和await是js的软关键字（可以当做变量名称的关键字），所以比较容易搞混

**Comment by zyxkad** [comment]
该问题已在 #149 解决
