### ISSUE TITLE
加入评论系统

### ISSUE THREAD

**Issue by zkitefly** [GlobeMC/crashmc.com#16]
使用 https://giscus.app/zh-CN 作为网站的评论系统我觉得可行，它是使用 GitHub Discussions 来存储评论，也可管理评论

**Comment by bingxin666** [comment]
> 使用 https://giscus.app/zh-CN 作为网站的评论系统我觉得可行，它是使用 GitHub Discussions 来存储评论，也可管理评论

@Big-Cake-jpg 你怎么看

**Comment by hejiehao** [comment]
顺便解决对于他们来说的疑难杂症

**Comment by zkitefly** [comment]
![image](https://github.com/GlobeMC/crashmc.com/assets/64117916/d5d036f1-b361-4640-a24c-4fef8c87710c)

**Comment by zkitefly** [comment]
那我加咯？
