### ISSUE TITLE
🙋[提议] 客户端介绍的文件目录处是否要为各启动器标出单独的目录树

### ISSUE THREAD

**Issue by MianSoft** [GlobeMC/crashmc.com#170]
这是我的代码(不知道能不能用
````
## 游戏文件 & 日志 <LauncherBadge type="bakaxl" text="仅 BakaXL" />

由 BakaXL 创建的游戏的文件目录一般如下所示。

```
.minecraft
├─$natives   <-本地库文件
│ └─...
├─assets
│ ├─indexes   <-资源索引文件
│ ├─objects   <-资源对象文件
│ │ └─...
│ └─skins   <-皮肤文件
│   └─...
├─libraries   <-依赖库
│ └─...
├─versions
│ ├─[版本名]
│ │ ├─crash-reports   <-崩溃报告
│ │ ├─logs   <-日志文件
│ │ ├─mods   <-模组文件
│ │ ├─resourcepacks   <-资源包
│ │ ├─saves   <-保存的游戏存档
│ │ │ └─[存档名]
│ │ │   ├─advancements   <-进度
│ │ │   ├─data   <-主世界数据
│ │ │   ├─datapacks   <-数据包
│ │ │   ├─DIM-1
│ │ │   │  ├─data   <-下界数据
│ │ │   │  ├─entities   <-下界数据
│ │ │   │  ├─poi   <-下界数据
│ │ │   │  └─region   <-下界数据
│ │ │   ├─DIM1
│ │ │   │  ├─data   <-末地数据
│ │ │   │  ├─entities   <-末地数据
│ │ │   │  ├─poi   <-末地数据
│ │ │   │  └─region   <-末地数据
│ │ │   ├─entities   <-主世界数据
│ │ │   ├─playerdata   <-玩家数据
│ │ │   ├─poi   <-主世界数据
│ │ │   ├─region   <-主世界数据
│ │ │   ├─serverconfig   <-服务器配置
│ │ │   └─stats   <-统计数据
│ │ ├─screenshots   <-游戏截图
│ │ └─...
│ └─[其他版本...]
└─...
```
````

**Comment by hejiehao** [comment]
你开 PR 你不就知道能不能用了

**Comment by bingxin666** [comment]
我觉得没有必要
或者说，可以把启动器特有的文件夹标上去，但不要写出来三个目录树......












---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年11月13日(周一) 凌晨2:28
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [GlobeMC/crashmc.com] 🙋[提议] 客户端介绍的文件目录处是否要为各启动器标出单独的目录树 (Issue #170)




 
这是我的代码(不知道能不能用
 ## 游戏文件 &amp; 日志 <LauncherBadge type="bakaxl" text="仅 BakaXL" /&gt; 由 BakaXL 创建的游戏的文件目录一般如下所示。 ``` .minecraft ├─$natives   <-本地库文件 │ └─... ├─assets │ ├─indexes   <-资源索引文件 │ ├─objects   <-资源对象文件 │ │ └─... │ └─skins   <-皮肤文件 │   └─... ├─libraries   <-依赖库 │ └─... ├─versions │ ├─[版本名] │ │ ├─crash-reports   <-崩溃报告 │ │ ├─logs   <-日志文件 │ │ ├─mods   <-模组文件 │ │ ├─resourcepacks   <-资源包 │ │ ├─saves   <-保存的游戏存档 │ │ │ └─[存档名] │ │ │   ├─advancements   <-进度 │ │ │   ├─data   <-主世界数据 │ │ │   ├─datapacks   <-数据包 │ │ │   ├─DIM-1 │ │ │   │  ├─data   <-下界数据 │ │ │   │  ├─entities   <-下界数据 │ │ │   │  ├─poi   <-下界数据 │ │ │   │  └─region   <-下界数据 │ │ │   ├─DIM1 │ │ │   │  ├─data   <-末地数据 │ │ │   │  ├─entities   <-末地数据 │ │ │   │  ├─poi   <-末地数据 │ │ │   │  └─region   <-末地数据 │ │ │   ├─entities   <-主世界数据 │ │ │   ├─playerdata   <-玩家数据 │ │ │   ├─poi   <-主世界数据 │ │ │   ├─region   <-主世界数据 │ │ │   ├─serverconfig   <-服务器配置 │ │ │   └─stats   <-统计数据 │ │ ├─screenshots   <-游戏截图 │ │ └─... │ └─[其他版本...] └─... ```

**Comment by bingxin666** [comment]
> 我也认为直接写出三个目录树多少是有点愚蠢(如果要写就用折叠文档吧x
> 不过目前文档里的目录树没有任何说明,还有一些mod生成的文件夹,最好还是去除这部分(?

赞同
目前目录树中的大部分目录对于我们解决游戏崩溃没啥用（例如objects or skins的子文件夹），可以考虑省略
@hejiehao @Pigeon0v0 @HRxiaohu

**Comment by zyxkad** [comment]
加上后大概也没有什么用，看看其他反馈

**Comment by MianSoft** [comment]
理解
