### ISSUE TITLE
机械动力升级崩溃

### ISSUE THREAD

**Issue by nianzhong** [GlobeMC/crashmc.com#171]
### 描述问题

```bash
机械动力从0.5.1e升级到0.5.1f后启动崩溃
```

### 您正在进行的操作是？

```bash
1. 
2. 
3. 
4. 游戏崩溃
```

### 崩溃日志

```bash
Description: Rendering overlay

org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
```

### 操作系统

Windows

### 客户端 / 服务端

客户端

**Comment by zyxkad** [comment]
请发送完整日志文件

**Comment by hejiehao** [comment]
你这日志给了跟没给一样

**Comment by nianzhong** [comment]
非常抱歉，现在已经解决了，是create附属模组create_central_kitchen-1.19.2-for-create-0.5.1.e-1.3.9.d不兼容create-1.19.2-0.5.1.f导致，感谢你的帮助。
崩溃文档附件已发送，请查收。




念
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "GlobeMC/crashmc.com"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月17日(星期五) 晚上10:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [GlobeMC/crashmc.com] 机械动力升级崩溃 (Issue #171)





 
你这日志给了跟没给一样

**Comment by hejiehao** [comment]
你知道吗：邮箱发附件 GitHub 不会显示

**Comment by nianzhong** [comment]
[crash-2023-11-17_10.44.16-client.txt](https://github.com/GlobeMC/crashmc.com/files/13398589/crash-2023-11-17_10.44.16-client.txt)
