### ISSUE TITLE
📄[UPLOAD-CRASH] 服务端+客户端崩溃问题

### ISSUE THREAD

**Issue by Luochancy** [GlobeMC/crashmc.com#203]
### 描述问题

```bash
服务端崩溃
疑似去区块生成错误
```

### 您正在进行的操作是？

```bash
1. 进入服务器
2. 加载地形
3. 服务端Crash
```

### 崩溃日志

```bash
如下文件
```

### 日志文件

[latest.log](https://github.com/GlobeMC/crashmc.com/files/14094682/latest.log)

### 操作系统

Linux

### 客户端 / 服务端

服务端

**Comment by Luochancy** [comment]
附本地图在客户端加载后崩溃的日志
[错误报告-2024-1-30_15.45.49.zip](https://github.com/GlobeMC/crashmc.com/files/14094696/-2024-1-30_15.45.49.zip)

**Comment by zyxkad** [comment]
应该是服务端代码问题，请升级到arclight最新版本，如果还不行请向arclight报告该问题
