### ISSUE TITLE
📄[UPLOAD-CRASH]Description: charTyped event handler

### ISSUE THREAD

**Issue by PureWhite202** [GlobeMC/crashmc.com#215]
### 描述问题

```bash
Description: charTyped event handler
```

### 您正在进行的操作是？

```bash
1. 正常游玩
2. 游戏崩溃
```

### 日志文件

[crash-2024-02-14_16.15.46-client.txt](https://github.com/GlobeMC/crashmc.com/files/14277007/crash-2024-02-14_16.15.46-client.txt)

### 操作系统

Windows

### 客户端 / 服务端

客户端

**Comment by zyxkad** [comment]
看起来是字体文件缺失，请向模组的github仓库提交issue

**Comment by PureWhite202** [comment]
> 看起来是字体文件缺失，请向模组的github仓库提交issue
问下能看出来是哪个模组的字体缺失吗？

**Comment by bingling-sama** [comment]
Cotton模组

> java.lang.NullPointerException: Cannot invoke "net.minecraft.class_327.method_27523(String, int)" because "this.font" is null
	at io.github.cottonmc.cotton.gui.widget.WTextField.scrollCursorIntoView(WTextField.java:151)
	at io.github.cottonmc.cotton.gui.widget.WTextField.insertText(WTextField.java:386)
	at io.github.cottonmc.cotton.gui.widget.WTextField.onCharTyped(WTextField.java:367)
	at red.jackf.chesttracker.gui.widgets.WUpdatableTextField.onCharTyped(WUpdatableTextField.java:21)

**Comment by bingling-sama** [comment]
建议您向 Cotton 模组提交 Issue 前优先检查您本地模组文件的 Hash 值是否与 Curseforge 上相同

**Comment by PureWhite202** [comment]
> 建议您向 Cotton 模组提交 Issue 前优先检查您本地模组文件的 Hash 值是否与 Curseforge/Modrinth 上相同

好的谢谢

**Comment by PureWhite202** [comment]
> 建议您向 Cotton 模组提交 Issue 前优先检查您本地模组文件的 Hash 值是否与 Curseforge/Modrinth 上相同

没找到装有cotton模组

**Comment by XieXiLin2** [comment]
如果您确信，请截图您的 「mods」 文件夹全部内容以便确认

**Comment by PureWhite202** [comment]
> 如果您确信，请截图您的 「mods」 文件夹全部内容以便确认

![image](https://github.com/GlobeMC/crashmc.com/assets/160005498/d95e7cc1-aa51-40ce-a20c-869195d216fa)
![image](https://github.com/GlobeMC/crashmc.com/assets/160005498/c143f9b4-c9a2-4a7a-9d98-64472235bd9b)
搜索io.github.cottonmc.cotton.gui.widget搜出一个叫LibGui也没有

**Comment by PureWhite202** [comment]
> 可以检查一下 `chesttracker` 模组

因为mod不影响玩法，所以我直接删除了
因为我也不知道崩溃的条件，有问题我再回来反馈
谢谢大佬

**Comment by bingling-sama** [comment]
可能有奇奇怪怪的冲突，如果有人有兴趣研究再 open 吧，close 了
