### ISSUE TITLE
📄[UPLOAD-CRASH] 服务器 1 tick 执行时间过长导致崩溃

### ISSUE THREAD

**Issue by SebasT1an796** [GlobeMC/crashmc.com#216]
### 描述问题

```bash
下线之前刷线机没关 恰好是出生点区块 所以有可能是实体太多导致卡崩 现在服务器进不去
```

### 您正在进行的操作是？

```bash
1. 挂机 
2. 游戏崩溃
```

### 日志文件

[crash-2024-02-14_17.22.00-server.txt](https://github.com/GlobeMC/crashmc.com/files/14290881/crash-2024-02-14_17.22.00-server.txt)

### 操作系统

Windows

### 客户端 / 服务端

服务端

**Comment by zyxkad** [comment]
解决方案:

调整 `server.properties` 文件，将 `max-tick-time` 值调高或设为 `-1`
