### ISSUE TITLE
📄[UPLOAD-CRASH] 解析聊天时出现 java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by xgvalley** [GlobeMC/crashmc.com#217]
### 描述问题

```bash
GlobeMC未收录我的崩溃信息。
```

### 您正在进行的操作是？

```bash
1. 使用HMCL打开Java版Minecraft的1.20.4版本，没有安装forge、fabric等。
2. 进入一个新的世界（无论是本地的地图还是服务器）
3. 游戏崩溃
4. 获取崩溃信息zip文件
5. 使用GlobeMC导入该zip文件
6. 显示的分析结果是：“本工具还未收录您所遇到的错误，请点击下方按钮前往 GitHub 反馈。”
```

### 日志文件

[minecraft-exported-crash-info-2024-02-03T10-42-20.zip](https://github.com/GlobeMC/crashmc.com/files/14303816/minecraft-exported-crash-info-2024-02-03T10-42-20.zip)

### 操作系统

Mac

### 客户端 / 服务端

客户端

**Comment by bingling-sama** [comment]
猜测为游戏文件损坏
> [10:41:56] [Render thread/ERROR]: Unreported exception thrown!
java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: 'java.lang.String com.mojang.authlib.properties.Property.getValue()'

**Comment by zyxkad** [comment]
等等，这issue咋开了两遍 :sweat:

**Comment by zyxkad** [comment]
虽然理论上我应该把这个关掉，但是 #207 没人理，我就把 #207 关了

**Comment by zkitefly** [comment]
该问题是由于当前版本的 `authlib-injector` 不支持 1.20.4 导致的崩溃，因为 HMCL 的自动选择下载源问题导致更新 `authlib-injector` 失败

先把 HMCL 换成这里下载的测试版本  https://gitee.com/Glavo/HMCL-Update#:~:text=.exe%EF%BC%9Ahmcl%2Ddev%2D ，然后在启动器的设置里，按图里的顺序去掉上面的勾，并且把下载源改成「BMCLAPI」，改完之后重启启动器 ![](https://img.kookapp.cn/assets/2023-08/rcKqsL83iv0m907d.png)

**Comment by xgvalley** [comment]
> 该问题是由于当前版本的 `authlib-injector` 不支持 1.20.4 导致的崩溃，因为 HMCL 的自动选择下载源问题导致更新 `authlib-injector` 失败
> 
> 先把 HMCL 换成这里下载的测试版本 https://gitee.com/Glavo/HMCL-Update#:~:text=.exe%EF%BC%9Ahmcl%2Ddev%2D ，然后在启动器的设置里，按图里的顺序去掉上面的勾，并且把下载源改成「BMCLAPI」，改完之后重启启动器 ![](https://camo.githubusercontent.com/3d83a2278cca1d1068139fc97355ec8169c92fac3d1eaec628b972ae2af8cd7f/68747470733a2f2f696d672e6b6f6f6b6170702e636e2f6173736574732f323032332d30382f72634b71734c38336976306d393037642e706e67)

问题已解决，非常感谢！
