### ISSUE TITLE
readme.md的stars和build爆炸了

### ISSUE THREAD

**Issue by bingxin666** [GlobeMC/crashmc.com#229]
如题，是不是之前把gh-pages删了导致的
![Screenshot_2024-02-19-16-50-01-916_com.github.android-edit.jpg](https://github.com/GlobeMC/crashmc.com/assets/73421892/bc8d8714-b79d-476e-bd70-b3be179fb1c2)

**Comment by bingling-sama** [comment]
你猜我为什么发 #226

**Comment by 2623684696** [comment]
stars要是直接访问是能出的
