### ISSUE TITLE
[UPLOAD-CRASH] 在服务端加载客户端 mod

### ISSUE THREAD

**Issue by FFDVDGD** [GlobeMC/crashmc.com#231]
### 描述问题

```bash
如题
附上chatgpt的分析，导致错误的mod分析的是正确的，细节就不清楚了


根据日志显示，服务器崩溃的主要原因是与Mod加载相关的问题，具体而言，是由于一个名为"Distant Horizons"的Mod加载失败导致的。在日志的末尾有一段错误消息:


net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
    Distant Horizons (distanthorizons) has failed to load correctly
    java.lang.reflect.InvocationTargetException: null
]
```

这表明"Distant Horizons" Mod加载时出现了问题。进一步的错误信息表明，在创建该Mod实例时发生了反射调用异常。

```
Caused by: java.lang.ExceptionInInitializerError
    at loaderCommon.forge.com.seibel.distanthorizons.common.wrappers.DependencySetup.createClientBindings(DependencySetup.java:69) ~[DistantHorizons-2.0.1-a-1.18.2.jar%2363!/:?]
    at com.seibel.distanthorizons.forge.ForgeMain.<init>(ForgeMain.java:98) ~[DistantHorizons-2.0.1-a-1.18.2.jar%2363!/:?]
    ... 11 more
Caused by: java.lang.RuntimeException: Attempted to load class net/minecraft/client/Minecraft for invalid dist DEDICATED_SERVER
```

这表明该Mod试图在服务器端加载客户端特定的类(net.minecraft.client.Minecraft)，这是不合理的，因为服务器端不应该加载客户端的类。

要解决这个问题，您可以尝试联系Mod作者或社区以获取支持，他们可能已经意识到了这个问题并提供了解决方案或更新。另外，您还可以尝试禁用或删除"Distant Horizons" Mod来查看服务器是否可以正常启动。
```


### 您正在进行的操作是？

```bash
1. 
2. 
3. 
4. 游戏崩溃
```

### 日志文件

https://mclo.gs/FcvT9q0

### 操作系统

Windows

### 客户端 / 服务端

服务端

**Comment by zyxkad** [comment]
虽然但是，分析 modid 好复杂，不是很想整

**Comment by bingling-sama** [comment]
> 虽然但是，分析 modid 好复杂，不是很想整

为啥会有分析mod id这一步

**Comment by bingling-sama** [comment]
> > 如果做到 mcla 里，是不是可以直接检测 Exception 中抛出的 class 是否为原版MC 的类
> 
> 是这样的，理论上只需要把错误的这个 class 上传到数据库就行
> 
> 但是，我发现这个日志的格式根其他我遇到的日志不一样，它错误那里有个缩进，我只会检测没有缩进的错误（）

还有这种原因吗……我没有阅读过 mcla 的代码，但是还是对日志分析与缩进有关感到不可思议

**Comment by FFDVDGD** [comment]
> > 如果做到 mcla 里，是不是可以直接检测 Exception 中抛出的 class 是否为原版MC 的类
> 
> 是这样的，理论上只需要把错误的这个 class 上传到数据库就行
> 
> 但是，我发现这个日志的格式根其他我遇到的日志不一样，它错误那里有个缩进，我只会检测没有缩进的错误（）

是forge的服务端
