### ISSUE TITLE
📄[UPLOAD-CRASH] java.lang.Error: Watchdog

### ISSUE THREAD

**Issue by Dospy-Honor** [GlobeMC/crashmc.com#236]
### 描述问题

```bash
Can't join in the game.
And server closed automaticly.
Server returned "Profiled not found user id"in client.
```

### 您正在进行的操作是？

```bash
什么也没干，直到崩溃时被用户通知
```

### 日志文件

[crash-2024-03-03_23.56.18-server.txt](https://github.com/GlobeMC/crashmc.com/files/14482484/crash-2024-03-03_23.56.18-server.txt)

### 操作系统

Linux

### 客户端 / 服务端

服务端

**Comment by Dospy-Honor** [comment]
> 看起来被 WatchDog 强制结束了。是否有使用 「模组加载器」 一类的东西？如果有，麻烦继续留言 「模组器名称、版本、模组列表」。 或者可能单纯是配置不足。

一个完全的官方服务器，服务器是cpu2 4GiB运行内存，虽然确实运行了很多红石内容，应该不至于坏掉吧

**Comment by zyxkad** [comment]
<img width="187" alt="Screenshot 2024-03-06 at 08 54 54" src="https://github.com/GlobeMC/crashmc.com/assets/91082411/65cb3bd4-decd-4abd-a6fa-f3ac9c7350a0">
27506个掉落物，不卡死才怪

**Comment by Dospy-Honor** [comment]
> <img alt="Screenshot 2024-03-06 at 08 54 54" width="187" src="https://private-user-images.githubusercontent.com/91082411/310565754-65cb3bd4-decd-4abd-a6fa-f3ac9c7350a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk3NDMyMzksIm5iZiI6MTcwOTc0MjkzOSwicGF0aCI6Ii85MTA4MjQxMS8zMTA1NjU3NTQtNjVjYjNiZDQtZGVjZC00YWJkLWE2ZmEtZjNhYzljNzM1MGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA2VDE2MzUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY1YTMyMzU1ODg5YTBkMWVjNmViNzkyY2VjZjFkYzZiODU1YWQ5ZjgxYWM3MjQ1ODQ2NTZiOTkwNzZlM2NhNzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CePR-ElSQDbs_BcMHS2mvc5y8T2FXYE6bdUXjyHjORc"> 27506个掉落物，不卡死才怪

坏了（（（（
咋办（（（

**Comment by Dospy-Honor** [comment]
重新开了一次服务器现在变成这样了
[crash-2024-03-06_21.21.24-server.txt](https://github.com/GlobeMC/crashmc.com/files/14513007/crash-2024-03-06_21.21.24-server.txt)

**Comment by bingling-sama** [comment]
用nbt修改器把这个区块删掉

**Comment by Dospy-Honor** [comment]
> 用nbt修改器把这个区块删掉

谢谢
