### ISSUE TITLE
📄[UPLOAD-CRASH] 是服务器崩溃

### ISSUE THREAD

**Issue by kevinluo6191** [GlobeMC/crashmc.com#246]
### 检查项

- [X] 我已检查并确认没有使用任何预览版的服务端 / 插件 / 模组
- [X] 我已确认位于 https://beta.crashmc.com/analyzer 的分析器无法找出我的错误 / 无法给出正确解法

### 描述问题

```bash
emmmmm 服务器崩溃
```

### 您正在进行的操作是？

```bash
1. 啥也没做
2. 
3. 
4. 游戏崩溃
```

### 日志文件

https://mclo.gs/dYTq2KN

### 操作系统

Windows

### 客户端 / 服务端

服务端

**Comment by bingxin666** [comment]
判断是某个实体导致服务端卡顿，导致被watchdog杀死
建议：删除实体

**Comment by kevinluo6191** [comment]
emmmmm 能帮忙确认是哪个实体么 
    
        
            
                
                    
                        
                    
                    
                        
                            Kevin Luo
                            
                            
                                
                                    ***@***.***
                                
                        
                    
                
            
        
    
---- 回复的原邮件 ***@***.***>发送日期2024年03月20日 14:03 ***@***.***> ***@***.***>***@***.***>主题Re: [GlobeMC/crashmc.com] 📄[UPLOAD-CRASH] 是服务器崩溃 (Issue #246)
判断是某个实体导致服务端卡顿，导致被watchdog杀死
建议：删除实体

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/GlobeMC/crashmc.com/issues/246#issuecomment-2008709091",
"url": "https://github.com/GlobeMC/crashmc.com/issues/246#issuecomment-2008709091",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by XieXiLin2** [comment]
Item / other
suggestion: 自己用 NBT Explorer 查查
