### ISSUE TITLE
📄[UPLOAD-CRASH] 飞跃星系的附属报错

### ISSUE THREAD

**Issue by jiniteimei** [GlobeMC/crashmc.com#250]
### 检查项

- [X] 我已检查并确认没有使用任何预览版的服务端 / 插件 / 模组
- [X] 我已确认位于 https://beta.crashmc.com/analyzer 的分析器无法找出我的错误 / 无法给出正确解法

### 描述问题

```bash
我的我的世界加了飞越星系的附属之后一直报错
```

### 您正在进行的操作是？

```bash
1. 
2. 
3. 
4. 游戏崩溃
```

### 日志文件

[Uploading 错误报告-2024-4-6_18.06.40.zip…]()

### 截图

![屏幕截图 2024-04-06 182303](https://github.com/GlobeMC/crashmc.com/assets/166216609/00baebb1-6b6b-4243-992c-6f7e61f17185)

### 操作系统

Windows

### 客户端 / 服务端

客户端

**Comment by Pigeon0v0** [comment]
缺少前置，这错误启动器都给你分析了...
