### ISSUE TITLE
📄[UPLOAD-CRASH] Mod Mixin 冲突

### ISSUE THREAD

**Issue by 8MiYile** [GlobeMC/crashmc.com#254]
### 检查项

- [X] 我已检查并确认没有使用任何预览版的服务端 / 插件 / 模组
- [X] 我已确认位于 https://beta.crashmc.com/analyzer 的分析器无法找出我的错误 / 无法给出正确解法

### 描述问题

```bash
来自崩溃报错群，因为看不懂，所以尝试使用工具 发现失败
```

### 您正在进行的操作是？

```bash
1. 
2. 
3. 
4. 游戏崩溃
```

### 日志文件

https://mclo.gs/jq1pMZl

### 操作系统

Windows

### 客户端 / 服务端

客户端

**Comment by zyxkad** [comment]
这是两个mod的mixin冲突了

**Comment by zyxkad** [comment]
解决方案，删除 `reach_entity_attributes` 或者 `valkyrienskies`

**Comment by 8MiYile** [comment]
哦哦好的 感谢

**Comment by XieXiLin2** [comment]
文档补充任务需要，暂时请勿关闭此 Issue。

**Comment by 8MiYile** [comment]
@XieXiLin2 哥们能否方便加我QQ 2671863036
