### ISSUE TITLE
📄[UPLOAD-CRASH] 未收录崩溃

### ISSUE THREAD

**Issue by bAdOoWindy** [GlobeMC/crashmc.com#277]
### 检查项

- [X] 我已检查并确认没有使用任何预览版的服务端 / 插件 / 模组
- [X] 我已确认位于 https://beta.crashmc.com/analyzer 的分析器无法找出我的错误 / 无法给出正确解法

### 描述问题

```bash
模组太多了，很难排查
```

### 您正在进行的操作是？

```bash
1. 打开游戏
2. 进入单人存档
3. 游戏崩溃
```

### 日志文件

[游戏崩溃](https://mclo.gs/nNc5OgS)

### 截图

![图片](https://github.com/GlobeMC/crashmc.com/assets/4119845/b4cb8833-17df-4506-8a99-db45e45fa6af)

解决办法

移除Grass Kiss模组

### 操作系统

Windows

### 客户端 / 服务端

服务端

**Comment by bingling-sama** [comment]
@bAdOoWindy 不是已经写出来了吗，有可能是grass kiss，litematica和malilib这些模组的问题

**Comment by bingling-sama** [comment]
看了一下貌似是mixin炸了，肯定有哪两个模组冲突了，是玩的整合包还是自己组合的模组？

**Comment by bAdOoWindy** [comment]
> @bAdOoWindy 不是已经写出来了吗，有可能是grass kiss，litematica和malilib这些模组的问题

有装Not Enough Crashes才有显示 ， 另外我这是在提交未收录的崩溃日志，不是找解决办法

**Comment by bingling-sama** [comment]
@bAdOoWindy 如果说是已解决的问题，麻烦您提交日志时最好也提交相应解决方案，因为我们不仅收录日志，也收录解决方案

**Comment by bAdOoWindy** [comment]
> @bAdOoWindy 如果说是已解决的问题，麻烦您提交日志时最好也提交相应解决方案，因为我们不仅收录日志，也收录解决方案

已添加解决办法
