### ISSUE TITLE
关于 Contributors 组件的修改事宜

### ISSUE THREAD

**Issue by bingling-sama** [GlobeMC/crashmc.com#283]
此前 @Big-Cake-jpg 将 Contributors 组件的实现方式更换为检索 git 提交日志来展示贡献者，本意是为了突出贡献者们的存在。但我认为先前的 Contributors 组件有另一重要作用是标明负责人，即在文档有异议或需更新时可以联系主要作者进行修改或酌取修改意见。希望对 Contributors 组件另行修改恢复功能，至于具体修改意见还请在本 Issue 下提出。

**Comment by Big-Cake-jpg** [comment]
可以自己改改，看看 Nolebase 集成的文档就行，把那个 git log 的 VitePress 插件扔掉然后按照 VitePress 文档全局插入组件的方法加回来即可。我没记错的话是没有删掉原来的 Contributors 组件的。

最近在忙自己的一个 Vue 项目，没有太多空余时间。

**Comment by bingling-sama** [comment]
我暂时在忙 blog 板块的开发，这个的话还是看你了，如果你没时间回头咱找别人搞一下

**Comment by bingling-sama** [comment]
在原有 Contributors 的基础上增设一个 Editor 如何？

**Comment by bingling-sama** [comment]
指根据 git log 生成贡献者列表的那个组件

**Comment by bingling-sama** [comment]
f0aa5f060e5d49990ad6e89d6b2da98692f3c624
