### ISSUE TITLE
📄[UPLOAD-CRASH] 服务端崩溃

### ISSUE THREAD

**Issue by frozengf** [GlobeMC/crashmc.com#289]
### 检查项

- [X] 我已检查并确认没有使用任何预览版的服务端 / 插件 / 模组
- [X] 我已确认位于 https://beta.crashmc.com/analyzer 的分析器无法找出我的错误 / 无法给出正确解法

### 描述问题

```bash
原本是在客户端开的本地服务器，然后老是崩溃，就换到服务端上面开服，然后过了一天又开始世界卡死了然后后台进程就终止了
```

### 您正在进行的操作是？

```bash
1. 开启服务器
2. 游玩一段时间
3. 游戏崩溃
```

### 日志文件

https://mclo.gs/w7RsCcV

### 操作系统

Windows

### 客户端 / 服务端

服务端

**Comment by zyxkad** [comment]
分析器已经检查出了该错误，并给出了正确解法
