### ISSUE TITLE
Blog 板块 post excerpt 部分无法自动省略多余部分

### ISSUE THREAD

**Issue by bingling-sama** [GlobeMC/crashmc.com#291]
如题，Blog 板块的 post card 中，显示的 excerpt 因无法自动省略多余部分导致元素过大溢出。   
需要其他开发者帮助修改。

**Comment by zyxkad** [comment]
.. 我之前不是说过用 text-overflow 么 https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow

另外，建议提供截图、代码、以及其他相关上下文

**Comment by bingling-sama** [comment]
> .. 我之前不是说过用 text-overflow 么 https://developer.mozilla.org/en-US/docs/Web/CSS/text-overflow
> 
> 另外，建议提供截图、代码、以及其他相关上下文

貌似并不生效，至于复现方式，只需在任意一篇文章的 excerpt 部分写上较长内容即可。
