### ISSUE TITLE
📄[UPLOAD-CRASH] 服务器崩溃！

### ISSUE THREAD

**Issue by mantianyouxian** [GlobeMC/crashmc.com#295]
### 检查项

- [X] 我已检查并确认没有使用任何预览版的服务端 / 插件 / 模组
- [X] 我已确认位于 https://beta.crashmc.com/analyzer 的分析器无法找出我的错误 / 无法给出正确解法

### 描述问题

```bash
服务器没玩家的时候，服务器可以稳定运行，不会报错，但服务器有玩家的时候，服务器会不定时进行报错!
我怀疑是模组的问题!
请求帮助！
谢谢！万分感谢！我代表服务器的全体玩家向您致谢！
```

### 您正在进行的操作是？

```bash
1. 走路
2. 挖掘方块
3. 挂机
4. 游戏崩溃
```

### 日志文件

https://[api.mclo.gs/1/raw/jn0E2dx](https://api.mclo.gs/1/raw/jn0E2dx)

### 操作系统

Linux

### 客户端 / 服务端

服务端

**Comment by bingling-sama** [comment]
@mantianyouxian 看起来像是服务器在尝试生成实体但出错了，注意到你有Carpet，是否改动了有关实体生成的options？

**Comment by mantianyouxian** [comment]
> 看起来像是服务器在尝试生成实体但出错了，注意到你有Carpet，是否改动了有关实体生成的选项？

是的！我开启了Carpet的“无卡顿生成 (lagFreeSpawning)”，我现在把它关了！ 感谢你的回答！ 我把服务器重新启动了起来，如果
