### ISSUE TITLE
📄[UPLOAD-CRASH] 未收錄的崩潰

### ISSUE THREAD

**Issue by ReimuKKSK** [GlobeMC/crashmc.com#296]
### 检查项

- [X] 我已检查并确认没有使用任何预览版的服务端 / 插件 / 模组
- [X] 我已确认位于 https://beta.crashmc.com/analyzer 的分析器无法找出我的错误 / 无法给出正确解法

### 描述问题

```bash
我的txtile backup原本是3.1.0-1.20的，然後我發現它無法正常備份
然後我去modrinth尋找有沒有新的版本，然後找到3.1.3-1.20的新版本
我就把原本的3.1.0換成3.1.3的新版本，重啟服務器，之後就崩潰了
已知 : 服務器地圖能加載，錯誤是在加載世界之後出現的，然後服務器崩潰後可以正常通過txtile backup生成備份文件
```

### 您正在进行的操作是？

```bash
1. 啟動服務器Bat檔
2. 服務器加載
3. 服務端UI出現
4. 服務端崩潰,UI關閉
5. Crtl+C終止Stop代碼自動重啟
```

### 日志文件

https://mclo.gs/D8M5DNS

### 操作系统

Windows

### 客户端 / 服务端

服务端

**Comment by bingling-sama** [comment]
@ReimuKKSK 貌似是txtile backup模组的mixin出现故障，有可能是与其他模组冲突了，建议向txtile backup模组官方报告此问题

**Comment by ReimuKKSK** [comment]
好，我有想過是不是txtile backup3.1.3調用了什麼不應該用的，畢竟3.1.0原本能備份的就是突然用不了了)
感謝！

**Comment by ReimuKKSK** [comment]
啊...應該是他的版本標的不好
3.1.0-1.20是fabric 1.20-1.20.1
3.1.3-1.20是fabric 1.20.4😅

**Comment by bingling-sama** [comment]
> 啊...應該是他的版本標的不好
> 3.1.0-1.20是fabric 1.20-1.20.1
> 3.1.3-1.20是fabric 1.20.4😅

居然报错不报版本不符？

**Comment by ReimuKKSK** [comment]
我看到也蒙了，(這也不應該啊？)
