### ISSUE TITLE
📄[UPLOAD-CRASH] 模组开发相关问题

### ISSUE THREAD

**Issue by DNightStars** [GlobeMC/crashmc.com#297]
### 检查项

- [x] 我已检查并确认没有使用任何预览版的服务端 / 插件 / 模组
- [X] 我已确认位于 https://beta.crashmc.com/analyzer 的分析器无法找出我的错误 / 无法给出正确解法

### 描述问题

```bash
我是fabric模组开发新手，我写了一个mod，通过IDEA运行runClient没有问题，但打包后运行便出现了java.lang.ClassNotFoundException: net.minecraft.util.registry.Registry
```

### 您正在进行的操作是？

```bash
1.
2.
3.
4. 游戏崩溃
```

### 日志文件

https://mclo.gs/d32Ldgy
mod源码
[MoreMinecraftItems.zip](https://github.com/user-attachments/files/16172023/MoreMinecraftItems.zip)

### 截图

![屏幕截图 2024-07-11 135337](https://github.com/GlobeMC/crashmc.com/assets/139193672/efde33c9-ec60-49f8-a27d-c6ff64cf9889)

### 操作系统

Windows

### 客户端 / 服务端

客户端

**Comment by bingling-sama** [comment]
我们并不提供模组开发问题答疑服务
