### ISSUE TITLE
📄服务器正常情况下崩溃

### ISSUE THREAD

**Issue by UNK1-JIU** [GlobeMC/crashmc.com#303]
### 检查项

- [X] 我已检查并确认没有使用任何预览版的服务端 / 插件 / 模组
- [X] 我已确认位于 https://beta.crashmc.com/analyzer 的分析器无法找出我的错误 / 无法给出正确解法

### 描述问题

```bash
MTR4.0.0 Beta-8 只有这个是测试版
```

### 您正在进行的操作是？

```bash
1. 正常游玩
2. 开飞机跑图：沉浸飞机
3. 走着开始卡 随后崩溃
4. 游戏崩溃
```

### 日志文件

https://mclo.gs/Wc7WAht

### 截图

无

### 操作系统

Windows

### 客户端 / 服务端

服务端

**Comment by XieXiLin2** [comment]
MTR 4.0 都还没出正式版 Release，有问题直接去 Discord 的 MTR 官服的 #preview-feedback 反馈。

**Comment by zyxkad** [comment]
不是这个，分析工具也能分析出来啊
