### ISSUE TITLE
用pcl启动mc，文件并未缺失，但不知道为什么进不去

### ISSUE THREAD

**Issue by bigplayersboss** [GlobeMC/crashmc.com#313]
### 检查项

- [X] 我已检查并确认没有使用任何预览版的服务端 / 插件 / 模组
- [X] 我已确认位于 https://beta.crashmc.com/analyzer 的分析器无法找出我的错误 / 无法给出正确解法

### 描述问题

```bash
我买的新笔记本电脑，硬件无问题，系统用heukms升级成了win11专业版，下的游戏例如mc无法进入，不知道什么原因，是系统原因吗？
```

### 您正在进行的操作是？

```bash
1. 
2. 
3. 
4. 游戏崩溃
```

### 日志文件

https://api.mclo.gs/1/raw/QISd9q8

### 操作系统

Windows

### 客户端 / 服务端

客户端

**Comment by bingling-sama** [comment]
@bigplayersboss 您提供的日志未包含任何有效信息

**Comment by bigplayersboss** [comment]
> @bigplayersboss 您提供的日志未包含任何有效信息

对啊，我也不知道为什么进不去，日志分析不出来

**Comment by bigplayersboss** [comment]
问题解决了，是我乱调系统注册表关杀毒搞得
