### ISSUE TITLE
📄[UPLOAD-CRASH] 请输入标题

### ISSUE THREAD

**Issue by Sczr0** [GlobeMC/crashmc.com#331]
### 检查项

- [X] 我已检查并确认没有使用任何预览版的服务端 / 插件 / 模组
- [X] 我已确认位于 https://beta.crashmc.com/analyzer 的分析器无法找出我的错误 / 无法给出正确解法

### 描述问题

```bash
进入服务器后崩溃
```

### 您正在进行的操作是？

```bash
1. 进入服务器
2. 四处走动
3. 
4. 游戏崩溃
```

### 日志文件

https://mclo.gs/imwk5GY

### 操作系统

Windows

### 客户端 / 服务端

客户端

**Comment by hejiehao** [comment]
游戏未响应吗？

**Comment by Sczr0** [comment]
不是，是突然崩溃

**Comment by Sczr0** [comment]
> 游戏未响应吗？

不是，是突然崩溃

**Comment by Sczr0** [comment]
其他窗口覆盖mc游戏界面或者让mc进入后台
[错误报告-2024-8-21_4.24.47.zip](https://github.com/user-attachments/files/16681590/-2024-8-21_4.24.47.zip)
可以稳定触发崩溃

**Comment by Sczr0** [comment]
根据mc返回的报错码找到了该链接
https://bugs.mojang.com/browse/MC-112780
更新英伟达8月20号发布的最新驱动后，三个小时的测试没有出现问题
