### ISSUE TITLE
分类问题

### ISSUE THREAD

**Issue by Seayay** [GlobeMC/crashmc.com#5]
[Forge 与 OptiFine 兼容性问题导致的崩溃](https://crashmc.com/clients.html#forge-%E4%B8%8E-optifine-%E5%85%BC%E5%AE%B9%E6%80%A7%E9%97%AE%E9%A2%98%E5%AF%BC%E8%87%B4%E7%9A%84%E5%B4%A9%E6%BA%83) 这一章节是否应该移至 [Forge](https://crashmc.com/clients.html#forge) 分类？毕竟 Fabric 不能用这个方法解决。

**Comment by bingxin666** [comment]
我觉得没必要
因为fabric与optifine的兼容性问题应该也会放在optifine那一栏里...

**Comment by Seayay** [comment]
> 我觉得没必要 因为fabric与optifine的兼容性问题应该也会放在optifine那一栏里...

指的是 Forge 与 OptiFine 兼容性问题导致的崩溃 这节，不是 OptiFine 一整节。

**Comment by bingxin666** [comment]
> > 我觉得没必要 因为fabric与optifine的兼容性问题应该也会放在optifine那一栏里...
> 
> 指的是 Forge 与 OptiFine 兼容性问题导致的崩溃 这节，不是 OptiFine 一整节。

optifine并不一定会作为模组来安装，因此放在optifine章节合适
而且你移过去了optifine写啥，~~opengl错误？~~

**Comment by Seayay** [comment]
> > > 我觉得没必要 因为fabric与optifine的兼容性问题应该也会放在optifine那一栏里...
> > 
> > 
> > 指的是 Forge 与 OptiFine 兼容性问题导致的崩溃 这节，不是 OptiFine 一整节。
> 
> optifine并不一定会作为模组来安装，因此放在optifine章节合适 而且你移过去了optifine写啥，~opengl错误？~

以模组形式安装了才能出现与 Forge 不兼容的情况吧，~Forge 不装模组？~

**Comment by bingxin666** [comment]
> > > > 我觉得没必要 因为fabric与optifine的兼容性问题应该也会放在optifine那一栏里...
> > > 
> > > 
> > > 指的是 Forge 与 OptiFine 兼容性问题导致的崩溃 这节，不是 OptiFine 一整节。
> > 
> > optifine并不一定会作为模组来安装，因此放在optifine章节合适 而且你移过去了optifine写啥，~opengl错误？~
> 
> 以模组形式安装了才能出现与 Forge 不兼容的情况吧，~Forge 不装模组？~

都会出现的，普遍现象，只是加载方式的不同

**Comment by 2623684696** [comment]
我还真这么干过（

**Comment by 2623684696** [comment]
不加mod（

**Comment by hejiehao** [comment]
> > > > > 我觉得没必要 因为fabric与optifine的兼容性问题应该也会放在optifine那一栏里...
> > > > 
> > > > 
> > > > 指的是 Forge 与 OptiFine 兼容性问题导致的崩溃 这节，不是 OptiFine 一整节。
> > > 
> > > 
> > > optifine并不一定会作为模组来安装，因此放在optifine章节合适 而且你移过去了optifine写啥，~opengl错误？~
> > 
> > 
> > 以模组形式安装了才能出现与 Forge 不兼容的情况吧，~Forge 不装模组？~
> 
> 都会出现的，普遍现象，只是加载方式的不同

再加一层

**Comment by Seayay** [comment]
> > > > > > 我觉得没必要 因为fabric与optifine的兼容性问题应该也会放在optifine那一栏里...
> > > > > 
> > > > > 
> > > > > 指的是 Forge 与 OptiFine 兼容性问题导致的崩溃 这节，不是 OptiFine 一整节。
> > > > 
> > > > 
> > > > optifine并不一定会作为模组来安装，因此放在optifine章节合适 而且你移过去了optifine写啥，~opengl错误？~
> > > 
> > > 
> > > 以模组形式安装了才能出现与 Forge 不兼容的情况吧，~Forge 不装模组？~
> > 
> > 
> > 都会出现的，普遍现象，只是加载方式的不同
> 
> 再加一层

禁止套娃

**Comment by bingxin666** [comment]
> > > > > > > 我觉得没必要 因为fabric与optifine的兼容性问题应该也会放在optifine那一栏里...
> > > > > > 
> > > > > > 
> > > > > > 指的是 Forge 与 OptiFine 兼容性问题导致的崩溃 这节，不是 OptiFine 一整节。
> > > > > 
> > > > > 
> > > > > optifine并不一定会作为模组来安装，因此放在optifine章节合适 而且你移过去了optifine写啥，~opengl错误？~
> > > > 
> > > > 
> > > > 以模组形式安装了才能出现与 Forge 不兼容的情况吧，~Forge 不装模组？~
> > > 
> > > 
> > > 都会出现的，普遍现象，只是加载方式的不同
> > 
> > 再加一层
> 
> 禁止套娃

套完，就en套

**Comment by 2623684696** [comment]
草

**Comment by Seayay** [comment]
> > > > > > > > 我觉得没必要 因为fabric与optifine的兼容性问题应该也会放在optifine那一栏里...
> > > > > > > 
> > > > > > > 
> > > > > > > 指的是 Forge 与 OptiFine 兼容性问题导致的崩溃 这节，不是 OptiFine 一整节。
> > > > > > 
> > > > > > 
> > > > > > optifine并不一定会作为模组来安装，因此放在optifine章节合适 而且你移过去了optifine写啥，~opengl错误？~
> > > > > 
> > > > > 
> > > > > 以模组形式安装了才能出现与 Forge 不兼容的情况吧，~Forge 不装模组？~
> > > > 
> > > > 
> > > > 都会出现的，普遍现象，只是加载方式的不同
> > > 
> > > 
> > > 再加一层
> > 
> > 
> > 禁止套娃
> 
> 套完，就en套

你也是套娃大师？

**Comment by Seayay** [comment]
~我提议不要再叠回复了~

**Comment by hejiehao** [comment]
> ~我提议不要再叠回复了~

~~我就叠~~

**Comment by bingxin666** [comment]
我觉得可以把所以涉及与optifine兼容性的内容都放到optifine一章里~~毕竟optifine太离谱了~~

**Comment by Seayay** [comment]
> 我觉得可以把所以涉及与optifine兼容性的内容都放到optifine一章里~毕竟optifine太离谱了~

可以，确实是 OptiFine 太爆炸导致的，那不改了

**Comment by 2623684696** [comment]
确实

**Comment by 2623684696** [comment]
都是optifine的离谱问题
