### ISSUE TITLE
contributing suggestions

### ISSUE THREAD

**Issue by bingling-sama** [GlobeMC/crashmc.com#86]
r u guys adding a new feature `crash log analyzer`?   
I have forked this repo and been working with it, but before I done u guys added something experimentally.   
that makes it very difficult for me to resolve the conflicts.
shouldn't that be in a `-patch` branch and merged into the main branch after finished?
I wouldn't like to fix those tough things in my future pr.

**Comment by bingling-sama** [comment]
@Big-Cake-jpg

**Comment by bingling-sama** [comment]
@Seayay

**Comment by Big-Cake-jpg** [comment]
We received your suggestions now and will try to make some changes. Let we know if you need help.

**Comment by bwtx2023** [comment]
Actually you can speak Chinese...

We thought this project would have no more contributors except us, so we usually do whatever we want. 

We will take your suggestions after the discussion and do more improvements. Thanks for your advice.

If you really use English as the first language, please ignore the Chinese part.

实际上你能说中文...

我们认为这个项目不会有除了我们以外更多贡献者参与进来，所以我们想做啥就做啥了。

我们将会在讨论之后采纳你的建议并作出更多改进。感谢你的反馈。

如果你确实把英语作为第一语言请忽略中文。

**Comment by bingling-sama** [comment]
thanks for that, that's great for u guys to take my advice.   
just close this issue after u finished restruction.
